# Regular users should NOT use this file! This is strictly for 
# this repository's testing!

# This workflow is used to test the bubbles-bot-gh/fast-forward action.
# It checksout the head reference of the pull request the workflow is run on, and then runs the 
# .github/actions/action.yml file.

name: Bubbles-Bot-GH Fast-Forward

on:
  pull_request:
    types: 
      - opened
  issue_comment:
    types:
      - created
      - edited

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  # This job checksout the head of the pull request and runs the fast-forward action on it.
  fast-forward:
    runs-on: ubuntu-latest
    environment: ci-testing
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        
      - name: Fast-Forward
        uses: ./action.yml
        with: 
          auto_merge: true
          post_comment: "always"
          custom_command: "/fast-forward"
      
  # This job cleans up 
  cleanup:
    needs:
      - fast-forward
    if: always() && startsWith(github.event.pull_request.head.ref, 'ci-test/')
    runs-on: ubuntu-latest
    environment: ci-testing
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        
      - name: Delete CI Test Branches
        run: |
          set -euo pipefail
          
          gh pr close "${{ github.event.issue.number }}" --repo "${{ github.repository }}" || true
          
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" \
            --delete "${{ github.event.pull_request.head_ref }}" || true
          
          git push "https://x-access-token; ${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" \
            --delete "${{ github.event.pull_request.base_ref }}" || true