# Regular users should NOT use this file! This is strictly for 
# this repository's testing!

name: Bubbles-Bot-GH Fast-Forward

on:
  pull_request:
    types: 
      - opened
  issue_comment:
    types:
      - created
      - edited

permissions:
  id-token: write
  
jobs:
  fast-forward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        
      - name: Fast-Forward
        uses: bubbles-bot-gh/fast-forward/action.yml@v1.0.0-alpha
        with: 
          auto_merge: true
          post_comment: "always"
          custom_command: "/fast-forward"